services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: oals/home-library-service-image
    container_name: home_library_service_cont
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - logs:/app/logs
    ports:
      - "${PORT}:${PORT}"
    networks:
      - home_network


  db:
    image: postgres:18-alpine
    container_name: home_library_service_db
    restart: unless-stopped
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_hls_data: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - home_network

volumes:
  db_data:
    name: home_library_service_data
  db_logs:
    name: home_library_service_db_logs
  logs:
    name: home_library_service_logs

networks:
  home_network:
    driver: bridge
    name: hls_network

